<a href="https://colab.research.google.com/github/NatalhyBB/Trabajo_pd/blob/main/Practica_calificada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EJERCICIO 1

Crea un vector de numeros enteros del 1 al 20

In [33]:
import numpy as np

vector = np.arange(1, 21)
print("Vector del 1 al 20:", vector)

Vector del 1 al 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Crea una matriz de 3x3 con valores aleatorios entre 0 y 1

In [32]:
import numpy as np
matriz_aleatoria = np.random.rand(3, 3)
print("Matriz 3x3 aleatoria:\n", matriz_aleatoria)


Matriz 3x3 aleatoria:
 [[0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504]
 [0.52889492 0.56804456 0.92559664]]


Redimensiona una matriz de 4x4 a una matriz de 2x8

In [31]:
import numpy as np
matriz_4x4 = np.arange(1, 17).reshape(4, 4)
matriz_2x8 = matriz_4x4.reshape(2, 8)
print("Matriz 4x4 original:\n", matriz_4x4)
print("Matriz redimensionada 2x8:\n", matriz_2x8)


Matriz 4x4 original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Matriz redimensionada 2x8:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


Crea un array de 10 múmeros equisitantes entre 0 y 1.

In [30]:
import numpy as np
equidistantes = np.linspace(0, 1, 10)
print("Array equidistante entre 0 y 1:", equidistantes)


Array equidistante entre 0 y 1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Concatena dos vectores verticales y horizontales

In [29]:
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Concatenación horizontal
concat_horizontal = np.concatenate((v1, v2))
print("Concatenación horizontal:", concat_horizontal)

# Concatenación vertical
v1_col = v1.reshape(-1, 1)
v2_col = v2.reshape(-1, 1)
concat_vertical = np.concatenate((v1_col, v2_col), axis=1)
print("Concatenación vertical:\n", concat_vertical)


Concatenación horizontal: [1 2 3 4 5 6]
Concatenación vertical:
 [[1 4]
 [2 5]
 [3 6]]


EJERCICIO 02

Calcula la suma, resta, multiplicación y división de dos vectores

In [28]:
import numpy as np

# Definimos dos vectores
v1 = np.array([10, 20, 30])
v2 = np.array([2, 5, 10])

# Suma
suma = v1 + v2

# Resta
resta = v1 - v2

# Multiplicación (elemento a elemento)
multiplicacion = v1 * v2

# División (elemento a elemento)
division = v1 / v2

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)


Suma: [12 25 40]
Resta: [ 8 15 20]
Multiplicación: [ 20 100 300]
División: [5. 4. 3.]


Calcula la media, mediana y desviación estándar de un vector

In [27]:
import numpy as np

# Definimos un vector
vector = np.array([10, 20, 30, 40, 50])

# Media (promedio)
media = np.mean(vector)

# Mediana
mediana = np.median(vector)

# Desviación estándar
desviacion_estandar = np.std(vector)

print("Media:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion_estandar)


Media: 30.0
Mediana: 30.0
Desviación estándar: 14.142135623730951


Normaliza un vector dividiendo cada elemento por el valor maximo

In [26]:
import numpy as np

vector = np.array([2, 4, 6, 8, 10])

maximo = np.max(vector)
vector_normalizado = vector / maximo

print("Vector original:", vector)
print("Vector normalizado:", vector_normalizado)


Vector original: [ 2  4  6  8 10]
Vector normalizado: [0.2 0.4 0.6 0.8 1. ]


Encuentra el indice del valor maximo y minimo en un vector

In [25]:
import numpy as np

vector = np.array([10, 25, 5, 40, 15])

indice_max = np.argmax(vector)
indice_min = np.argmin(vector)

print("Índice del valor máximo:", indice_max)
print("Índice del valor mínimo:", indice_min)


Índice del valor máximo: 3
Índice del valor mínimo: 2


Realiza una multiplicación matricial entre dos matrices 3x3

In [24]:
import numpy as np

# Definimos dos matrices 3x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Multiplicación matricial
C = np.matmul(A, B)

print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Multiplicación matricial A x B:\n", C)


Matriz A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Multiplicación matricial A x B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


EJERCICIO 03

Selecciona los elementos pares de un vector de números

In [23]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Seleccionar elementos pares
pares = vector[vector % 2 == 0]

print("Elementos pares:", pares)


Elementos pares: [ 2  4  6  8 10]


Filtra los valores mayores que 5 en un vector

In [22]:
import numpy as np

vector = np.array([2, 5, 7, 3, 9, 1, 6])

# Filtrar valores mayores que 5
mayores_que_5 = vector[vector > 5]

print("Valores mayores que 5:", mayores_que_5)


Valores mayores que 5: [7 9 6]


Filtra los valores iguales a cero

In [21]:
import numpy as np

vector = np.array([0, 1, 2, 0, 3, 0, 4, 5])

# Filtrar valores iguales a cero
ceros = vector[vector == 0]

print("Valores iguales a cero:", ceros)


Valores iguales a cero: [0 0 0]


Filtra los valores negativos

In [20]:
import numpy as np

vector = np.array([3, -1, 7, -5, 0, -2, 4])

# Filtrar valores negativos
negativos = vector[vector < 0]

print("Valores negativos:", negativos)

Valores negativos: [-1 -5 -2]


Aplica la media a los valores mayores a 50

In [19]:
import numpy as np

vector = np.array([10, 55, 70, 45, 90, 30, 60])

# Filtrar valores mayores a 50
mayores_50 = vector[vector > 50]

# Calcular la media de esos valores
media_mayores_50 = np.mean(mayores_50)

print("Valores mayores a 50:", mayores_50)
print("Media de valores mayores a 50:", media_mayores_50)


Valores mayores a 50: [55 70 90 60]
Media de valores mayores a 50: 68.75


EJERCICIO 04

Crea un vector de 10 elementos y reemplaza todos los valores mayores que 5 con 0

In [18]:
import numpy as np

# Crear un vector de 10 elementos
vector = np.arange(1, 11)
print("Vector original:", vector)

# Reemplazar valores mayores que 5 con 0
vector[vector > 5] = 0

print("Vector modificado:", vector)


Vector original: [ 1  2  3  4  5  6  7  8  9 10]
Vector modificado: [1 2 3 4 5 0 0 0 0 0]


Combina dos vectores booleanos utilizando las operaciones & y |

In [17]:
import numpy as np

# Definimos dos vectores booleanos
v1 = np.array([True, False, True, False])
v2 = np.array([True, True, False, False])

# Operación AND
and_resultado = v1 & v2

# Operación OR
or_resultado = v1 | v2

print("v1:", v1)
print("v2:", v2)
print("AND (v1 & v2):", and_resultado)
print("OR (v1 | v2):", or_resultado)


v1: [ True False  True False]
v2: [ True  True False False]
AND (v1 & v2): [ True False False False]
OR (v1 | v2): [ True  True  True False]


Cuenta la cantidad de valores en un vector que son multiplos de 3

In [16]:
import numpy as np

vector = np.array([3, 5, 9, 12, 14, 18, 20, 21])

# Condición para múltiplos de 3
multiplos_de_3 = vector[vector % 3 == 0]

# Contar cuántos hay
cantidad = multiplos_de_3.size

print("Valores múltiplos de 3:", multiplos_de_3)
print("Cantidad de múltiplos de 3:", cantidad)

Valores múltiplos de 3: [ 3  9 12 18 21]
Cantidad de múltiplos de 3: 5


Encuentra los indices de los elementos no nulos en un vector

In [15]:
import numpy as np

vector = np.array([0, 2, 0, 5, 6, 0, 7])

# Obtener índices de elementos no nulos
indices_no_nulos = np.nonzero(vector)[0]

print("Índices de elementos no nulos:", indices_no_nulos)


Índices de elementos no nulos: [1 3 4 6]


Comprueba si todos los elemntos en un array son mayores que un valor especifico digitado por el usuario

In [14]:
import numpy as np

# Definimos un array
array = np.array([10, 20, 30, 40, 50])

valor = float(input("Ingresa un valor para comparar: "))

# Comprobar si todos los elementos son mayores que el valor
resultado = np.all(array > valor)

if resultado:
    print(f"Todos los elementos son mayores que {valor}")
else:
    print(f"No todos los elementos son mayores que {valor}")


Ingresa un valor para comparar: 12
No todos los elementos son mayores que 12.0


EJERICICO 05

Calcula el cuadrado de cada elemento en un vector

In [13]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])

cuadrado = vector ** 2

print("Vector original:", vector)
print("Cuadrado de cada elemento:", cuadrado)

Vector original: [1 2 3 4 5]
Cuadrado de cada elemento: [ 1  4  9 16 25]


Utiliza la funcion exponencial para elevar todos los elementos de un vector a la misma potencia

In [12]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])

# Definir la potencia
potencia = 3

# Elevar todos los elementos a la potencia
resultado = np.power(vector, potencia)

print("Vector original:", vector)
print(f"Vector elevado a la potencia {potencia}:", resultado)


Vector original: [1 2 3 4 5]
Vector elevado a la potencia 3: [  1   8  27  64 125]


  Encuentra los valores máximos y mínimos en cada fila de una matriz

In [11]:
import numpy as np

# Crear una matriz
matriz = np.array([[5, 2, 8, 1],
                   [7, 9, 3, 4],
                   [6, 0, 2, 5]])

# Máximos por fila
maximos_filas = np.max(matriz, axis=1)

# Mínimos por fila
minimos_filas = np.min(matriz, axis=1)

print("Matriz:\n", matriz)
print("Máximos por fila:", maximos_filas)
print("Mínimos por fila:", minimos_filas)


Matriz:
 [[5 2 8 1]
 [7 9 3 4]
 [6 0 2 5]]
Máximos por fila: [8 9 6]
Mínimos por fila: [1 3 0]


Aplica la función sin a todos los elementos de un vector a la misma potencia

In [10]:
import numpy as np

vector = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

potencia = 2
# Aplicar sin a cada elemento y luego elevar al cuadrado
resultado = np.power(np.sin(vector), potencia)

print("Vector original (radianes):", vector)
print(f"sin(vector) elevado a la potencia {potencia}:", resultado)


Vector original (radianes): [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sin(vector) elevado a la potencia 2: [0.   0.25 0.5  0.75 1.  ]


Realiza la transpuesta de una matriz 3x4

In [9]:
import numpy as np

matriz = np.array([[2, 4, 5, 6],
                   [1, 2, 4, 5],
                   [4, 5, 7, 8]])

transpuesta = matriz.T

print("Matriz original:\n", matriz)
print("Transpuesta:\n", transpuesta)

Matriz original:
 [[2 4 5 6]
 [1 2 4 5]
 [4 5 7 8]]
Transpuesta:
 [[2 1 4]
 [4 2 5]
 [5 4 7]
 [6 5 8]]


EJERCICIO 06

Crea un DataFrame con las siguientes columnas: Nombre, Edad, Ciudad. Añade al menos 10 registros

In [8]:
import pandas as pd

datos = {
    'Nombre': ['Ana', 'Luis', 'Carla', 'Pedro', 'Marta', 'Jorge', 'Sofía', 'Carlos', 'Lucía', 'Diego'],
    'Edad': [25, 30, 22, 35, 28, 40, 23, 33, 27, 31],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao', 'Madrid', 'Granada', 'Valencia', 'Sevilla', 'Barcelona']
}

df = pd.DataFrame(datos)

print("DataFrame original:")
print(df)

# 1. Filtrar personas que tienen más de 25 años
mayores_25 = df[df['Edad'] > 25]
print("\nPersonas con más de 25 años:")
print(mayores_25)

# 2. Añadir una nueva columna llamada Ingresos y rellenarla
import numpy as np
np.random.seed(0)
df['Ingresos'] = np.random.randint(1000, 5000, size=len(df))
print("\nDataFrame con columna 'Ingresos':")
print(df)

# 3. Encontrar el promedio de la edad
promedio_edad = df['Edad'].mean()
print(f"\nPromedio de edad: {promedio_edad:.2f}")

# 4. Agrupar por 'Ciudad' y calcular el promedio de Edad para cada ciudad
promedio_edad_ciudad = df.groupby('Ciudad')['Edad'].mean()
print("\nPromedio de edad por ciudad:")
print(promedio_edad_ciudad)

# 5. Ordenar el DataFrame por 'Edad' de manera ascendente
df_asc = df.sort_values(by='Edad', ascending=True)
print("\nDataFrame ordenado por Edad (ascendente):")
print(df_asc)

# Ordenar el DataFrame por 'Edad' de manera descendente
df_desc = df.sort_values(by='Edad', ascending=False)
print("\nDataFrame ordenado por Edad (descendente):")
print(df_desc)


DataFrame original:
   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2   Carla    22   Valencia
3   Pedro    35    Sevilla
4   Marta    28     Bilbao
5   Jorge    40     Madrid
6   Sofía    23    Granada
7  Carlos    33   Valencia
8   Lucía    27    Sevilla
9   Diego    31  Barcelona

Personas con más de 25 años:
   Nombre  Edad     Ciudad
1    Luis    30  Barcelona
3   Pedro    35    Sevilla
4   Marta    28     Bilbao
5   Jorge    40     Madrid
7  Carlos    33   Valencia
8   Lucía    27    Sevilla
9   Diego    31  Barcelona

DataFrame con columna 'Ingresos':
   Nombre  Edad     Ciudad  Ingresos
0     Ana    25     Madrid      3732
1    Luis    30  Barcelona      3607
2   Carla    22   Valencia      2653
3   Pedro    35    Sevilla      4264
4   Marta    28     Bilbao      1835
5   Jorge    40     Madrid      1763
6   Sofía    23    Granada      2731
7  Carlos    33   Valencia      4431
8   Lucía    27    Sevilla      2033
9   Diego    31  Barcelona      

EJERCICIO 07

In [7]:
import pandas as pd

# Leer el archivo Excel
df = pd.read_excel('/content/universidad.xlsx')
print(df.head()) #Comprobar

# 1. Cantidad de estudiantes en Ingeniería en Sistemas
cantidad_sistemas = df[df['Carrera'] == 'Ing. en sistemas'].shape[0]

# 2. Cantidad de estudiantes en Lic. en derecho
cantidad_derecho = df[df['Carrera'] == 'Lic. en derecho'].shape[0]

# 3. Cantidad de estudiantes inscritos en el año 2015
# Primero extraemos el año de la columna 'Inscripción'
df['Año'] = pd.DatetimeIndex(df['Inscripción']).year
cantidad_2015 = df[df['Año'] == 2015].shape[0]

# 4. Cantidad de estudiantes del 1er y 2do semestre
semestres_1_2 = df[df['Semestre'].isin([1, 2])]
conteo_semestres = semestres_1_2.groupby('Semestre').size().reset_index(name='Cantidad').sort_values('Semestre')

# Resultados
print(f"\nCantidad de estudiantes en Ingeniería en sistemas: {cantidad_sistemas}")
print(f"Cantidad de estudiantes en Lic. en derecho: {cantidad_derecho}")
print(f"Cantidad de estudiantes inscritos en 2025: {cantidad_2015}")

print("\nCantidad de estudiantes por semestre (1 y 2):")
print(conteo_semestres.to_string(index=False))


  Num Control              Carrera  Semestre Inscripción  Id Persona
0    SeNeTe01  Lic. en nutriología         7  2015-05-20           1
1    JeViPi02         Ing. química         8  2015-05-02           2
2    MaFeNú03      Lic. en derecho         6  2015-05-09           3
3    WiVaLó04     Ing. en sistemas         2  2016-12-03           4
4    BaRiDe05     Ing. mecatrónica        10  2018-12-01           5

Cantidad de estudiantes en Ingeniería en sistemas: 13
Cantidad de estudiantes en Lic. en derecho: 17
Cantidad de estudiantes inscritos en 2025: 23

Cantidad de estudiantes por semestre (1 y 2):
 Semestre  Cantidad
        1        11
        2        11
